cto_homepage:
    path:     /
    defaults: { _controller: CTOBundle:Default:index }

cto_list_news:
  path:  /news
  defaults: { _controller: CTOBundle:News:index}

cto_delete_news:
  path:    /news/{id}/delete
  defaults: { _controller: CTOBundle:News:delete }
  requirements:
    id: \d+

cto_create_news:
   path:  /news/create
   defaults: { _controller: CTOBundle:News:create}

cto_edit_news:
   path:  /news/{id}/edit
   defaults: { _controller: CTOBundle:News:edit}
   requirements:
    id: \d+

cto_author_delete:
   path:  /author/{id}/delete
   defaults: { _controller: CTOBundle:Author:delete}
   requirements:
    id: \d+

cto_authors_list:
   path:  /authors
   defaults: { _controller: CTOBundle:Author:index}

cto_author_edit:
  path: /author/{id}/edit
  defaults: { _controller: CTOBundle:Author:edit}
  requirements:
   id: \d+

cto_author_create:
  path: /author/create
  defaults: { _controller: CTOBundle:Author:create}
