CTOBundle\Entity\News:
    type: entity
    table: news
    repositoryClass: CTOBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        description:
            type: text
        dateCreate:
            type: datetimetz
            column: date_create
        dateUpdate:
            type: datetimetz
            nullable: true
            column: date_update
        urlArticle:
            type: string
            length: 255
            nullable: true
            column: url_article
        urlImage:
            type: string
            length: 255
            nullable: true
            column: url_image
    lifecycleCallbacks: {  }
    manyToOne:
            author:
                targetEntity: CTOBundle\Entity\Author
                inversedBy: authors
                joinColumn:
                    name: author_id
                    referencedColumnName: id
    manyToMany:
        tags:
          targetEntity: Tags
          joinTable:
            name: news_tag
            joinColumns:
              news_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id
