<?php

namespace CTOBundle\Repository;

use CTOBundle\Entity\Author;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository implements NewsAPI
{
    public function existByName($name)
    {
        $author = $this->findOneBy(array("name" => $name));
        if ($author != null) {
            return $author;
        }
        return null;
    }

    public function createFromNewsApi(array $params)
    {
        $author = new Author();
        $author->setName($params["author"]);
        $author->setDateCreate(date_create());
        $author->setDateUpdate(date_create());
        $this->_em->persist($author);
        $this->_em->flush();
        if ($author->getId()) {
            return $author;
        }
        return null;
    }
}
