<?php

namespace CTOBundle\Repository;

use CTOBundle\Entity\News;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Prophecy\Util\StringUtil;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository implements NewsAPI
{
    public function createFromNewsApi(array $param)
    {
        if ( !empty($param["title"]) )
        {
            $news = new News();
            $news->setName($param["title"]);
            $news->setAuthor($param["author"]);
            if ( !empty($param["description"]) )
            {
                $news->setDescription($param["description"]);
            }

            if ( !empty($param["date_create"]) ) {
                $news->setDateCreate(date_create($param["date_create"]));
                $news->setDateUpdate(date_create($param["date_create"]));
            }
            else
            {
                $news->setDateCreate(date_create());
                $news->setDateUpdate(date_create());
            }
            if ( !empty($param["url"]) )
            {
                $news->setUrlArticle($param["url"]);
            }
            if ( !empty($param["urlToImage"]) )
            {
                $news->setUrlImage($param["urlToImage"]);
            }
            if ( !empty( $param["tag"]) ) {
                $news->setTags($param["tag"]);
            }
            $this->_em->persist($news);
            $this->_em->flush();

        }
    }

    public function existByName($name)
    {
        if ($this->findOneBy(array("name" => $name)) != null) {
            return true;
        }
        return false;
    }


}
