<?php

namespace CTOBundle\Repository;

use CTOBundle\Entity\Tags;
use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository implements NewsAPI
{
    public function createFromNewsApi(array $param)
    {
        if ( !empty($param["name"]) )
        {
            $tag = new Tags();
            $tag->setName($param["name"]);
            $tag->setDateCreate(date_create());
            $tag->setDateUpdate(date_create());
            $this->_em->persist($tag);
            $this->_em->flush();
            if ( $tag->getId() )
            {
                return $tag;
            }
            return null;
        }
    }

    public function existByName($name)
    {
        $tag = $this->findOneBy(array("name" => $name));
        if ($tag != null) {
            return $tag;
        }
        return null;
    }

}
